// flow-typed signature: 2d156fe7b8c416e17a55a597c90f5967
// flow-typed version: <<STUB>>/@material/icon-button_v^0.42.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/icon-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/icon-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/icon-button/adapter' {
  declare module.exports: any;
}

declare module '@material/icon-button/constants' {
  declare module.exports: any;
}

declare module '@material/icon-button/dist/mdc.iconButton' {
  declare module.exports: any;
}

declare module '@material/icon-button/dist/mdc.iconButton.min' {
  declare module.exports: any;
}

declare module '@material/icon-button/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/icon-button/adapter.js' {
  declare module.exports: $Exports<'@material/icon-button/adapter'>;
}
declare module '@material/icon-button/constants.js' {
  declare module.exports: $Exports<'@material/icon-button/constants'>;
}
declare module '@material/icon-button/dist/mdc.iconButton.js' {
  declare module.exports: $Exports<'@material/icon-button/dist/mdc.iconButton'>;
}
declare module '@material/icon-button/dist/mdc.iconButton.min.js' {
  declare module.exports: $Exports<'@material/icon-button/dist/mdc.iconButton.min'>;
}
declare module '@material/icon-button/foundation.js' {
  declare module.exports: $Exports<'@material/icon-button/foundation'>;
}
declare module '@material/icon-button/index' {
  declare module.exports: $Exports<'@material/icon-button'>;
}
declare module '@material/icon-button/index.js' {
  declare module.exports: $Exports<'@material/icon-button'>;
}
