// flow-typed signature: 329e8226417ccfed5461227fb85421ba
// flow-typed version: <<STUB>>/@material/react-top-app-bar_v^0.7.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/react-top-app-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/react-top-app-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/react-top-app-bar/dist/index' {
  declare module.exports: any;
}

declare module '@material/react-top-app-bar/dist/index.min' {
  declare module.exports: any;
}

declare module '@material/react-top-app-bar/dist/top-app-bar.css' {
  declare module.exports: any;
}

declare module '@material/react-top-app-bar/dist/top-app-bar.es' {
  declare module.exports: any;
}

declare module '@material/react-top-app-bar/dist/top-app-bar.min.css' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/react-top-app-bar/dist/index.js' {
  declare module.exports: $Exports<'@material/react-top-app-bar/dist/index'>;
}
declare module '@material/react-top-app-bar/dist/index.min.js' {
  declare module.exports: $Exports<'@material/react-top-app-bar/dist/index.min'>;
}
declare module '@material/react-top-app-bar/dist/top-app-bar.css.js' {
  declare module.exports: $Exports<'@material/react-top-app-bar/dist/top-app-bar.css'>;
}
declare module '@material/react-top-app-bar/dist/top-app-bar.es.js' {
  declare module.exports: $Exports<'@material/react-top-app-bar/dist/top-app-bar.es'>;
}
declare module '@material/react-top-app-bar/dist/top-app-bar.min.css.js' {
  declare module.exports: $Exports<'@material/react-top-app-bar/dist/top-app-bar.min.css'>;
}
