// flow-typed signature: 32047f5061e8bc2f23b7d0457672b44f
// flow-typed version: <<STUB>>/@material/react-card_v^0.7.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/react-card'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/react-card' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/react-card/dist/card.css' {
  declare module.exports: any;
}

declare module '@material/react-card/dist/card.es' {
  declare module.exports: any;
}

declare module '@material/react-card/dist/card.min.css' {
  declare module.exports: any;
}

declare module '@material/react-card/dist/index' {
  declare module.exports: any;
}

declare module '@material/react-card/dist/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/react-card/dist/card.css.js' {
  declare module.exports: $Exports<'@material/react-card/dist/card.css'>;
}
declare module '@material/react-card/dist/card.es.js' {
  declare module.exports: $Exports<'@material/react-card/dist/card.es'>;
}
declare module '@material/react-card/dist/card.min.css.js' {
  declare module.exports: $Exports<'@material/react-card/dist/card.min.css'>;
}
declare module '@material/react-card/dist/index.js' {
  declare module.exports: $Exports<'@material/react-card/dist/index'>;
}
declare module '@material/react-card/dist/index.min.js' {
  declare module.exports: $Exports<'@material/react-card/dist/index.min'>;
}
