// flow-typed signature: fdf94e1b6e9e43cde3a2a3a43f03f44f
// flow-typed version: <<STUB>>/@material/react-material-icon_v^0.7.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/react-material-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/react-material-icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/react-material-icon/dist/index' {
  declare module.exports: any;
}

declare module '@material/react-material-icon/dist/index.min' {
  declare module.exports: any;
}

declare module '@material/react-material-icon/dist/material-icon.css' {
  declare module.exports: any;
}

declare module '@material/react-material-icon/dist/material-icon.es' {
  declare module.exports: any;
}

declare module '@material/react-material-icon/dist/material-icon.min.css' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/react-material-icon/dist/index.js' {
  declare module.exports: $Exports<'@material/react-material-icon/dist/index'>;
}
declare module '@material/react-material-icon/dist/index.min.js' {
  declare module.exports: $Exports<'@material/react-material-icon/dist/index.min'>;
}
declare module '@material/react-material-icon/dist/material-icon.css.js' {
  declare module.exports: $Exports<'@material/react-material-icon/dist/material-icon.css'>;
}
declare module '@material/react-material-icon/dist/material-icon.es.js' {
  declare module.exports: $Exports<'@material/react-material-icon/dist/material-icon.es'>;
}
declare module '@material/react-material-icon/dist/material-icon.min.css.js' {
  declare module.exports: $Exports<'@material/react-material-icon/dist/material-icon.min.css'>;
}
