// flow-typed signature: 6f7af56b44cd5222e1fe28507b312119
// flow-typed version: <<STUB>>/@material/react-button_v^0.7.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/react-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/react-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/react-button/dist/button.css' {
  declare module.exports: any;
}

declare module '@material/react-button/dist/button.es' {
  declare module.exports: any;
}

declare module '@material/react-button/dist/button.min.css' {
  declare module.exports: any;
}

declare module '@material/react-button/dist/index' {
  declare module.exports: any;
}

declare module '@material/react-button/dist/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/react-button/dist/button.css.js' {
  declare module.exports: $Exports<'@material/react-button/dist/button.css'>;
}
declare module '@material/react-button/dist/button.es.js' {
  declare module.exports: $Exports<'@material/react-button/dist/button.es'>;
}
declare module '@material/react-button/dist/button.min.css.js' {
  declare module.exports: $Exports<'@material/react-button/dist/button.min.css'>;
}
declare module '@material/react-button/dist/index.js' {
  declare module.exports: $Exports<'@material/react-button/dist/index'>;
}
declare module '@material/react-button/dist/index.min.js' {
  declare module.exports: $Exports<'@material/react-button/dist/index.min'>;
}
